# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  tinyshooter_config = debug
endif
ifeq ($(config),release)
  tinyshooter_config = release
endif

PROJECTS := tinyshooter

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

tinyshooter:
ifneq (,$(tinyshooter_config))
	@echo "==== Building tinyshooter ($(tinyshooter_config)) ===="
	@${MAKE} --no-print-directory -C . -f tinyshooter.make config=$(tinyshooter_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f tinyshooter.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   tinyshooter"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"